### ISSUE TITLE
Docker: Provide sample docker-compose.yml, especially on hub.docker.com

### ISSUE THREAD

**Issue by diamondsw** [szabodanika/microbin#135]
Right now only a partial compose file is provided, and it does not show how to use command-line options. I recommend a better example that matches the command-line examples, for instance:

```
version: "3"
services:
  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    restart: unless-stopped
    command: >
      --public-path 'https://myserver.net'
      --highlightsyntax
      --editable
    ports:
     - '8080:8080'
    volumes:
     - ./data:/app/pasta_data
```

**Comment by ItsNoted** [comment]
You can use this one I made too.

```
services:
  paste:
    image: danielszabo99/microbin
    restart: always
    environment:
     - MICROBIN_PRIVATE=true
     - MICROBIN_PUBLIC_PATH=https://mysite.com #remove this if running locally but you wont be able to copy links or use QR.
     - MICROBIN_QR=true
     - MICROBIN_HIGHLIGHTSYNTAX=true
     - MICROBIN_AUTH_USERNAME=admin
     - MICROBIN_AUTH_PASSWORD=password
     - MICROBIN_TITLE=noted.lol
     - MICROBIN_QR=True
     - MICROBIN_HIDE_FOOTER=True
    ports:
     - "8065:8080"
    volumes:
     - /docker/microbin:/my/microbin
     - /docker/microbin/data:/app/pasta_data #mounting database.json for persistent DB.
```
