### ISSUE TITLE
.env file provided by docker-setup.sh has incorrect examples

### ISSUE THREAD

**Issue by decaby7e** [szabodanika/microbin#188]
Example:

```
# Hides the navigation bar on every page.
# Default value: 8080
export MICROBIN_HIDE_HEADER=false

# Hides the footer on every page.
# Default value: 8080
export MICROBIN_HIDE_FOOTER=false

# Hides the MicroBin logo from the navigation bar on every
# page.
# Default value: 8080
export MICROBIN_HIDE_LOGO=false

# Disables the /pastalist endpoint, essentially making all
# pastas private.
# Default value: 8080
export MICROBIN_NO_LISTING=false
```

**Comment by szabodanika** [comment]
Yeah, those are definitely not the actual default values. I think in the documentation I fixed these but apparently not in the default .env? Thanks for catching this and letting me know! By the way, all boolean variables have false as their default value.

**Comment by simonl169** [comment]
I have a problem that is probably related to this.
I use docker-compose with Portainer to deploy ma instance.
I only use a few env-variables, like admin-PW, those are set correctly, but the ones I dont set (to get the default values/settings) dont match the defaults in the documentation, eg. Syntax-highlighting

**Comment by szabodanika** [comment]
@simonl169 that sounds annoying, can you say which ones seem to have different defaults from what's documented in the .env file? I should fix these ASAP

**Comment by simonl169** [comment]
I believe its basically every variable. Everyone is set to false or unset, except those I manually set.
I screenshotted them and marked which I set manually, I unfortunately dont have time to compare to the documentation

![Screenshot from 2023-07-16 13-25-18](https://github.com/szabodanika/microbin/assets/98774388/ac1bfec3-2839-4f2a-a2f4-27cbb11ac94d)


I also append my docker-compose:


```
services:
  paste:
    image: danielszabo99/microbin:2.0.4
    restart: always
    ports:
     - "9013:8080"
    volumes:
     - microbin-data:/app/pasta_data
    environment:
      MICROBIN_ADMIN_USERNAME: redacted
      MICROBIN_ADMIN_PASSWORD: redacted
      MICROBIN_HIGHLIGHTSYNTAX: true
      MICROBIN_DEFAULT_EXPIRY: 1week
 
volumes:
  microbin-data:  
```

Maybe the standard .env file inside the container is not loaded correctly?
