### ISSUE TITLE
Pass arguments when using docker-compose?

### ISSUE THREAD

**Issue by streiman** [szabodanika/microbin#99]
I just found microbin and like it very much. Deployed it using docker-compose. The docker image works perfect and I can access microbin, even using traefik.

But there are several options like --public-path --private or --qr - how can I pass them to microbin using docker-compose.yaml? I couldn't find anything in the documentation.

**Comment by szabodanika** [comment]
Hello, every flag is also available as an environment variable. See https://github.com/szabodanika/microbin/blob/master/src/args.rs. I will put this into the documentation asap

**Comment by streiman** [comment]
Thanks, that works perfectly.

**Comment by luxus** [comment]
can i use a .env where the docker-compose.yml is?
because that is not working for me
````sh
export MICROBIN_DEFAULT_BURN_AFTER=1
export MICROBIN_DEFAULT_EXPIRY=1week
export MICROBIN_EDITABLE=false
export MICROBIN_ENABLE_BURN_AFTER=true
export MICROBIN_HIDE_FOOTER=true
export MICROBIN_HIDE_HEADER=true
export MICROBIN_HIGHLIGHTSYNTAX=true
export MICROBIN_NO_ETERNAL_PASTA=true
export MICROBIN_NO_LISTING=true
export MICROBIN_PRIVATE=true
export MICROBIN_PUBLIC_PATH="http//:example.com:8088"
export MICROBIN_QR=true
export MICROBIN_TITLE="Dropsecret"
````

**Comment by Jimmy2027** [comment]
Thanks! I managed with this docker-compose.yml file (starting service with `docker compose up -d`):

```yml

services:
  paste:
    image: microbin-docker
    restart: always
    env_file:
      - /my/microbin/.env
    ports:
     - "8080:8080"
    volumes:
     - ./microbin-data:/my/microbin

```
and this `/my/microbin/.env` file:
```
MICROBIN_TITLE="Hello World"
MICROBIN_QR=True
MICROBIN_HIDE_FOOTER=True

```
